name: First Workflow
on: workflow_dispatch # allow to run workflow manually
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done-Bye!"
      - name: multiline comments
        run: |
          echo "First output"
          echo "Second output"
      
