name: First Workflow
on: workflow_dipatch # this will make sure that, we can manually trigger the workflow
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done-Bye!"
      
